import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Announcemenet from './ui/announcemenet';

import NavbarMain from "./ui/navbar";
import Navbar from "./ui/navbarTalwind";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/*     <Providers> */}
      <Announcemenet />
      <Navbar />
      <div className="flex h-screen flex-col">
        {children}
      </div>
      {/*    </Providers> */}
    </html>
  );
}
